name: Push to buf.build

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**/*.proto'
      - 'buf.yaml'
      - 'buf.lock'

jobs:
  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to buf.build
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push