name: Proto Quality & Breaking Change Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: |
        # Install buf
        curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o buf
        chmod +x buf
        sudo mv buf /usr/local/bin/
        
        # Install protolint
        go install github.com/yoheimuta/protolint/cmd/protolint@latest
    
    - name: Update buf dependencies
      run: cd proto && buf dep update
    
    - name: Run all checks
      run: make check

  breaking-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for breaking change detection
    
    - name: Install buf
      run: |
        curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o buf
        chmod +x buf
        sudo mv buf /usr/local/bin/
    
    - name: Check for breaking changes
      run: |
        echo "Checking for breaking changes against main branch..."
        cd proto && buf breaking --against '../.git#branch=main'